db.retete.insert({
    nume: "",
    origine_url: "",
    origine_limba: "en",
    origine: "www.jamieoliver.com",
    origine_carte: "",
    etichete: [""],
    persoane: 4,
    timp: ,
    nivel: 1,
    limba: "ro",
    nutritie: [{
        calorii: ,
        carbohidrati: ,
        zahar: ,
        grasimi: ,
        grasimi_saturate: ,
        proteine:
    }],
    ingrediente: [{
        pentru: "",
        lista: [{
            nume: "",
            cantitate: ,
            um: "",
            categorie: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: "",
            comentariu: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: "",
            comentariu: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: "",
            comentariu: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: "",
            comentariu: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: "",
            comentariu: ""
        }, {
            nume: "",
            cantitate: ,
            um: "",
            categorie: "",
            comentariu: ""
        }]
    }],
    instructiuni: [{
        ordine: 1,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }, {
        ordine: ,
        text: ""
    }]
})